### ISSUE TITLE
error on launching plugin in RB2.99+ & 3.0

### ISSUE THREAD

**Issue by fossfreedom** [kingd/looper#6]
The new checkbox is causing an issue

<pre>
Traceback (most recent call last):
  File "/home/dad/.local/share/rhythmbox/plugins/looper/looper.py", line 92, in do_activate
    self.create_widgets()
  File "/home/dad/.local/share/rhythmbox/plugins/looper/looper.py", line 130, in create_widgets
    self.button.set_related_action(self.action.action)
TypeError: argument action: Expected Gtk.Action, but got gi.repository.Gio.SimpleAction
</pre>

the attempt to assign the action to the button does not work because it is a Gio.SimpleAction not a Gtk.Action - in RB2.99 and later, menus use the latter object type.  In RB2.98 and earlier, Gtk.Action is used - hence why you could do a button.set_related_action(action) before but you cannot now.

I would recommend that you use a button instead

        self.button = Gtk.Button.new_with_label('Close')
        #self.button.set_related_action(self.action.action)
        self.button.connect('clicked', self.on_button_clicked)

        def on_button_clicked(self, *args):
            self.action.activate()

Move this to the end of the hbox

I was going to do a pull request but I came across the following issue as well.

If you click the "Always show Looper GUI" in the preferences you have the following issue...

1. the Toggle menu option just toggles on-off but the GUI stays - a bit confusing.

2. the proposed close button is visible but clicking it nothing happens because the GUI remains always visible.

Maybe the better option would be to change "Always show Looper GUI" to actually be "Show Looper on start of rhythmbox" - thus start with looper on by default - but you can turn it off via the close button.

**Comment by kingd** [comment]
Activation button should now be available in RB3
