### ISSUE TITLE
on/off button

### ISSUE THREAD

**Issue by fossfreedom** [kingd/looper#8]
just checked out the latest changes.

By default the button labelled "off" is displayed - to switch on looper you have to the click "off" button

Can I suggest the label be switched to "on"?

**Comment by kingd** [comment]
Thanks David. Yes it is kind of weird. It depends if it is an action or a state. I always regarded it as a state but unfortunately ToggleButton cannot be used. I changed the labels to Enabled/Disabled. Please change as you feel appropriate for you as it is now easily changeable with constants ON_LABEL and OFF_LABEL.
