### ISSUE TITLE
save loop button

### ISSUE THREAD

**Issue by fossfreedom** [kingd/looper#9]
think maybe the number of loops be limited somehow?

if you repeatedly click the save loop button more and more loops saving options are displayed - you could click the button 100 times and 100 save options are displayed.  Is this intentional?

Also - clicking "save loop" - when the number of loops spills into a separate line, the save loop button gets larger - maybe switch off the button.expand option?

**Comment by kingd** [comment]
Yes, I limited the loop number to 32. It really depends on the width of the screen. Initially I wanted to make it a ScrolledWindow so you can have unlimited loops, but for some reason it is not working. For me, with this setup, the main window goes to hell(shrinks) after 40 loops (6th row).

What you mean 100 save options are displayed? You mean loop boxes, the ones you wanted limited number? Many loops per song are OK (32 maximum now)

I am not experiencing the issue with save loop button getting bigger. I tried making expand to False but it is really ugly then, any combination of the two buttons. It is a simple change, please customize to your preference.

**Comment by fossfreedom** [comment]
yes - those changes are much better.  Thanks.

I'll upload the new version to my PPA.

BTW - At some point if I find some time I'll see if I can make this plugin work with my plugin alternative-toolbar.
